name: Test On Push

on:
    push:
        branches:
        - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup Go
          uses: actions/setup-go@v3
        - uses: actions/checkout@v3
        - name: Get Dagger
          run: go get dagger.io/dagger@latest
        - name: Run Dagger Test Workflow
          run: go run ci/test_on_push.go